### ISSUE TITLE
[handpose] Missing takes from test split

### ISSUE THREAD

**Issue by MichaelRamamonjisoa** [EGO4D/ego-exo4d-egopose#3]
When running Step 6 of the data_preparation procedure for handpose estimation, I'm running into the following error:

```
  File "/private/home/micramamonjisoa/ego-exo4d-egopose/handpose/data_preparation/main.py", line 144, in extract_aria_img
    assert len(take) == 1, f"Take: {take_uid} does not exist"
           ^^^^^^^^^^^^^^
AssertionError: Take: 2e657e9a-17b4-4387-8f6f-9c7484a8504d does not exist
```

After careful checking, it seems like the following takes are in the [ego_pose_gt_anno_test_public.json](https://github.com/EGO4D/ego-exo4d-egopose/blob/main/handpose/data_preparation/ego_pose_gt_anno_test_public.json) file but are missing from the `takes.json` file that is downloaded when downloading ego4d metadata:

```
Missing takes:  ['2e657e9a-17b4-4387-8f6f-9c7484a8504d', '0ffe3d64-3afe-456f-829e-45fc51e50dc4']
```

These correspond respectively to the sequences `upenn_0407_Violin_3_3` and `iiith_cooking_107_4`

Is it expected? Will testing crash if I choose to ignore these takes?

**Comment by ssh37010** [comment]
Thanks for your feedback. We are looking into the issue.

**Comment by miguelmartin75** [comment]
You seem to be using the V1 version of `takes.json`. If you use V2's `takes.json` you should not encounter this error.

Please upgrade your `ego4d` pip package: `pip install --upgrade ego4d` and then run `egoexo -o <dir> --parts metadata`. You may want to look at the documentation on what to download: https://docs.ego-exo4d-data.org/download/

**Comment by MichaelRamamonjisoa** [comment]
Works, thank you!
