### ISSUE TITLE
What's going on with the benchmarks gaining?

### ISSUE THREAD

**Issue by ACondaway** [EGO4D/ego-exo4d-egopose#5]
![6fe6f42b6b9ff9245264f2ea2eaee5c](https://github.com/EGO4D/ego-exo4d-egopose/assets/115391544/d56bc355-599b-4bc5-916e-f8073ca27f15)

**Comment by ACondaway** [comment]
When I try body_pose as documentation shows, still meet the same problem.

**Comment by Sky-Wang326** [comment]
similar problem, I get invalid benchmarks for hand_pose. Is there any solution?
The command I'm running is: `egoexo -o MY_PATH --parts annotations metadata --benchmarks hand_pose`
![image](https://github.com/EGO4D/ego-exo4d-egopose/assets/65812436/2bcbe0bd-bbc1-49bd-81d5-89f5592c203a)

**Comment by gaperezsa** [comment]
We are having problems trying to replicate the  issue:
<img width="1438" alt="Captura de pantalla 2024-05-16 a la(s) 5 37 51 p m" src="https://github.com/EGO4D/ego-exo4d-egopose/assets/56688374/d03de928-3446-4411-87a8-6d0188f94a10">

can you check your was client is set up correctly and you are no using a VPN perhaps?

**Comment by miguelmartin75** [comment]
What version of the CLI are you using?

**Comment by chaitanya100100** [comment]
@miguelmartin75 I am also getting the same 'invalid benchmark' error with the same command. I have upgraded to ego4d==1.16.0 and still getting the same error.

**Comment by miguelmartin75** [comment]
Yes, this was a subtle bug on my end. I have fixed this issue in `1.7.3` apologies for the inconvenience. PR: https://github.com/facebookresearch/Ego4d/pull/336 

Related issue: https://github.com/facebookresearch/Ego4d/issues/334
